# ============================================================================
# Univariate SpecialFunctions
# Auto-generated by deps/generate_specialfunctions.jl using Symbolics.jl
# ============================================================================

ExaModels.@register_univariate(
    SpecialFunctions.erf,
    x -> (2 * _cinvsqrtpi(x)) * exp(-(x^2)),
    x -> -(4 * _cinvsqrtpi(x)) * x * exp(-(x^2)),
)
ExaModels.@register_univariate(
    SpecialFunctions.erfc,
    x -> -(2 * _cinvsqrtpi(x)) * exp(-(x^2)),
    x -> (4 * _cinvsqrtpi(x)) * x * exp(-(x^2)),
)
ExaModels.@register_univariate(
    SpecialFunctions.erfi,
    x -> (2 * _cinvsqrtpi(x)) * exp(x^2),
    x -> (4 * _cinvsqrtpi(x)) * x * exp(x^2),
)
ExaModels.@register_univariate(
    SpecialFunctions.erfcx,
    x -> 2(-_cinvsqrtpi(x) + x * SpecialFunctions.erfcx(x)),
    x -> 2(SpecialFunctions.erfcx(x) + 2x * (-_cinvsqrtpi(x) + x * SpecialFunctions.erfcx(x))),
)
ExaModels.@register_univariate(
    SpecialFunctions.digamma,
    x -> SpecialFunctions.trigamma(x),
    x -> SpecialFunctions.polygamma(2, x),
)
ExaModels.@register_univariate(
    SpecialFunctions.trigamma,
    x -> SpecialFunctions.polygamma(2, x),
    x -> SpecialFunctions.polygamma(3, x),
)
ExaModels.@register_univariate(
    SpecialFunctions.invdigamma,
    x -> 1 / SpecialFunctions.trigamma(SpecialFunctions.invdigamma(x)),
    x -> (-SpecialFunctions.polygamma(2, SpecialFunctions.invdigamma(x))) / (SpecialFunctions.trigamma(SpecialFunctions.invdigamma(x))^3),
)
ExaModels.@register_univariate(
    SpecialFunctions.gamma,
    x -> SpecialFunctions.gamma(x) * SpecialFunctions.digamma(x),
    x -> SpecialFunctions.gamma(x) * (SpecialFunctions.trigamma(x) + SpecialFunctions.digamma(x)^2),
)
ExaModels.@register_univariate(
    SpecialFunctions.airyai,
    x -> SpecialFunctions.airyaiprime(x),
    x -> x * SpecialFunctions.airyai(x),
)
ExaModels.@register_univariate(
    SpecialFunctions.airybi,
    x -> SpecialFunctions.airybiprime(x),
    x -> x * SpecialFunctions.airybi(x),
)
ExaModels.@register_univariate(
    SpecialFunctions.airyaiprime,
    x -> x * SpecialFunctions.airyai(x),
    x -> SpecialFunctions.airyai(x) + x * SpecialFunctions.airyaiprime(x),
)
ExaModels.@register_univariate(
    SpecialFunctions.airybiprime,
    x -> x * SpecialFunctions.airybi(x),
    x -> SpecialFunctions.airybi(x) + x * SpecialFunctions.airybiprime(x),
)
ExaModels.@register_univariate(
    SpecialFunctions.besselj0,
    x -> -SpecialFunctions.besselj1(x),
    x -> (-SpecialFunctions.besselj0(x) + SpecialFunctions.besselj(2, x)) / 2,
)
ExaModels.@register_univariate(
    SpecialFunctions.bessely0,
    x -> -SpecialFunctions.bessely1(x),
    x -> (-SpecialFunctions.bessely0(x) + SpecialFunctions.bessely(2, x)) / 2,
)
ExaModels.@register_univariate(
    SpecialFunctions.besselj1,
    x -> (SpecialFunctions.besselj0(x) - SpecialFunctions.besselj(2, x)) / 2,
    x -> ((-SpecialFunctions.besselj(1, x) + SpecialFunctions.besselj(3, x)) / 2 - SpecialFunctions.besselj1(x)) / 2,
)
ExaModels.@register_univariate(
    SpecialFunctions.bessely1,
    x -> (SpecialFunctions.bessely0(x) - SpecialFunctions.bessely(2, x)) / 2,
    x -> ((SpecialFunctions.bessely(3, x) - SpecialFunctions.bessely(1, x)) / 2 - SpecialFunctions.bessely1(x)) / 2,
)
ExaModels.@register_univariate(
    SpecialFunctions.dawson,
    x -> 1 - 2x * SpecialFunctions.dawson(x),
    x -> -2SpecialFunctions.dawson(x) - 2x * (1 - 2x * SpecialFunctions.dawson(x)),
)

# Manual entries (Symbolics.jl cannot auto-derive these)
ExaModels.@register_univariate(
    SpecialFunctions.erfinv,
    x -> _csqrtpihalf(x) * exp(SpecialFunctions.erfinv(x)^2),
    x -> _csqrtpihalf(x) * exp(SpecialFunctions.erfinv(x)^2) * 2 * SpecialFunctions.erfinv(x) * _csqrtpihalf(x) * exp(SpecialFunctions.erfinv(x)^2),
)
ExaModels.@register_univariate(
    SpecialFunctions.erfcinv,
    x -> -_csqrtpihalf(x) * exp(SpecialFunctions.erfcinv(x)^2),
    x -> (_cpi(x) / 2) * SpecialFunctions.erfcinv(x) * exp(2 * SpecialFunctions.erfcinv(x)^2),
)

# ============================================================================
# Bivariate SpecialFunctions
# Auto-generated by deps/generate_specialfunctions.jl using Symbolics.jl
# ============================================================================

ExaModels.@register_bivariate(
    SpecialFunctions.beta,
    (x1, x2) -> SpecialFunctions.beta(x1, x2) * (SpecialFunctions.digamma(x1) - SpecialFunctions.digamma(x1 + x2)),
    (x1, x2) -> SpecialFunctions.beta(x1, x2) * (-SpecialFunctions.digamma(x1 + x2) + SpecialFunctions.digamma(x2)),
    (x1, x2) -> SpecialFunctions.beta(x1, x2) * (SpecialFunctions.trigamma(x1) - SpecialFunctions.trigamma(x1 + x2) + (SpecialFunctions.digamma(x1) - SpecialFunctions.digamma(x1 + x2))^2),
    (x1, x2) -> -SpecialFunctions.beta(x1, x2) * SpecialFunctions.trigamma(x1 + x2) + SpecialFunctions.beta(x1, x2) * (SpecialFunctions.digamma(x1) - SpecialFunctions.digamma(x1 + x2)) * (-SpecialFunctions.digamma(x1 + x2) + SpecialFunctions.digamma(x2)),
    (x1, x2) -> SpecialFunctions.beta(x1, x2) * (-SpecialFunctions.trigamma(x1 + x2) + SpecialFunctions.trigamma(x2) + (-SpecialFunctions.digamma(x1 + x2) + SpecialFunctions.digamma(x2))^2),
)
ExaModels.@register_bivariate(
    SpecialFunctions.logbeta,
    (x1, x2) -> SpecialFunctions.digamma(x1) - SpecialFunctions.digamma(x1 + x2),
    (x1, x2) -> -SpecialFunctions.digamma(x1 + x2) + SpecialFunctions.digamma(x2),
    (x1, x2) -> SpecialFunctions.trigamma(x1) - SpecialFunctions.trigamma(x1 + x2),
    (x1, x2) -> -SpecialFunctions.trigamma(x1 + x2),
    (x1, x2) -> -SpecialFunctions.trigamma(x1 + x2) + SpecialFunctions.trigamma(x2),
)
